

language: node_js
node_js:
 - "node"
#  services:
#   - postgresql
#  before_script:
#   - psql -c 'create database travis_ci_test;' -U postgres
# after_success:
#   - npm run coverage
#   - npm run report-coverage
 # after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

#  env:
#   global:
#     - CC_TEST_REPORTER_ID=f9d06acc600fa14bc78db4810c60e2173f21b6407095a56c6c2a9cdc22055b7a
# language: ruby
# rvm:
#   - 2.2.0
# before_script:
#   - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
#   - chmod +x ./cc-test-reporter
#   - ./cc-test-reporter before-build
# script:
#   - bundle exec rspec
# after_script:
#   - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT


# language: node_js
# env:
#   global:
#     - CC_TEST_REPORTER_ID=f9d06acc600fa14bc78db4810c60e2173f21b6407095a56c6c2a9cdc22055b7a
#
# node_js:
#   - "node"
# dist: trusty
# addons:
#   chrome: stable
# before_script:
#   - yarn global add nyc
#   - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
#   - chmod +x ./cc-test-reporter
#   - ./cc-test-reporter before-build
#
# script:
#   - nyc --reporter=lcov yarn run unit
#
# after_script:
#   - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
#
# notifications:
#   email: false
